#'原名' = [ '译名', 出现次数 ]

"サトル" = ["悟", 4332]
"オルガ" = ["奥尔嘉", 1624]
"ピエレッタ" = ["佩蕾塔", 1471]
"ティア" = ["蒂娅", 1233]
"さやか" = ["沙耶香", 1184]
"美齢" = ["美龄", 1028]
"ベルローネ" = ["贝尔罗妮", 818]
"アルライネ" = ["阿尔莱妮", 721]
"ケネス" = ["肯尼斯", 165]
"宿の女将" = ["旅馆老板娘", 49]
"？？？" = ["？？？", 32]
"メイド" = ["女仆", 26]
"少女の声" = ["少女之声", 18]
"謎の声" = ["神秘之声", 13]
"艶のある女" = ["艳女", 12]
"名家の娘たち" = ["名门千金们", 6]
"旅する女" = ["旅行的女子", 6]
"ブリンガー" = ["布林格", 5]
"おさげの少女" = ["麻花辫少女", 4]
"腹黒い少女" = ["腹黑少女", 4]
"白い少女" = ["白衣少女", 4]
"女性の声" = ["女性之声", 1]
"リリー" = ["莉莉", 1]
"全員" = ["全员", 1]
